/**
 * Signal Explainer Service
 * 
 * Takes raw quantitative signals generated by the Scanner Engine
 * and uses DeepSeek to generate a human-readable, institutional-grade explanation.
 */
import { aiClient } from '../deepseek';
import { SYSTEM_PROMPTS, TASK_PROMPTS } from '../prompts/registry';
import { db } from '../../../lib/db';
import { aiSignalAnalysis } from '../../../lib/db/schema';
import { redis } from '../../../lib/redis';
import { logger } from '../../../lib/logger';

export class SignalExplainer {
  
  async explainSignal(symbol: string, signalId: string, signalType: string, contextData: any) {
    try {
      // 1. Check if we already explained this signal
      const cached = await redis.get(`ai:signal:${signalId}`);
      if (cached) return JSON.parse(cached);

      logger.info('SignalExplainer', `Generating explanation for ${symbol} - ${signalType}`);

      // 2. Format Context
      const contextStr = JSON.stringify({
        timestamp: new Date().toISOString(),
        ...contextData
      }, null, 2);

      // 3. Generate Analysis
      const prompt = TASK_PROMPTS.EXPLAIN_SIGNAL(symbol, signalType, contextStr);
      const response = await aiClient.generate(prompt, SYSTEM_PROMPTS.INSTITUTIONAL_ANALYST);

      // 4. Determine pseudo-confidence from text (simple heuristic, AI could return JSON in a v2)
      let pseudoConfidence = 50;
      if (response.content.toLowerCase().includes('strong conviction') || response.content.toLowerCase().includes('highly probable')) {
        pseudoConfidence += 30;
      }

      const record = {
        symbol,
        signalId,
        signalType,
        explanation: response.content,
        confidence: pseudoConfidence,
        risks: "Derived from explanation", // In a structured AI response, we'd split this
        modelUsed: response.model,
        tokensUsed: response.tokens.total,
      };

      // 5. Persist to Postgres
      await db.insert(aiSignalAnalysis).values(record);

      // 6. Cache in Redis (TTL 24 hours since signals expire anyway)
      await redis.setex(`ai:signal:${signalId}`, 86400, JSON.stringify(record));
      
      // 7. Emit Event for Frontend WebSocket
      await redis.publish('ai:stream:signal_explanation', JSON.stringify(record));

      return record;
    } catch (error) {
      logger.error('SignalExplainer', `Failed to explain signal ${signalId}`, error);
      throw error;
    }
  }
}

export const signalExplainer = new SignalExplainer();
